# xis02.conf -- xindiserver instance "xis02", running on magaox02
#
# Local drivers only -- see xis01.conf for why there's no remote/
# tunnel configuration here.

[indiserver]
f = /opt/MagAOX/drivers/fifos/indiserver.ctrl
#p = 7624
v = v,v,v
z = false

####################################
### Only local INDI driver on 7624 INDI server is magAOXMaths
### Local drivers connect on start by sending start command to INDI
### server control FIFO (.ctrl, above), but putting the local driver
### here will ensure crashed INDI server will also try to restart local
### drivers
####################################

[local]
drivers=c02,d02

####################################
### No connection to remote drivers
### via remote INDI servers
####################################
#
[remote]

